/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-11-21 03:14:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/components/top.jsp", out, false);
      out.write("\n");
      out.write("	\n");
      out.write("	  <div class=\"site-wrap\">\n");
      out.write("	  \n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/components/nav.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"site-blocks-cover\" data-aos=\"fade\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-6 ml-auto order-md-2 align-self-start\">\n");
      out.write("            <div class=\"site-block-cover-content\">\n");
      out.write("         <h2 class=\"title\" style=\"color: #CF793C;\">Sorvetes que fazem seus sonhos derreterem</h2>\n");
      out.write("		 <h1 style=\"color: #CF793C;\">BDL</h1>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-6 order-1 align-self-end\">\n");
      out.write("            <img src=\"https://o.remove.bg/downloads/d6cfe9fd-316d-4387-9ecd-652b7651fbf0/sorvetinho-removebg-preview.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("    <div class=\"site-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"title-section mb-5 col-12\">\n");
      out.write("      <h2 class=\"text-uppercase\">Conheça nossos produtos</h2>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"row\">\n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Bacio-di-Latte.png\" alt=\"Ninho\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Ninho</a></h2>\n");
      out.write("      <strong class=\"item-price\">R$20.00</strong>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Cioccolato-Belga.png\" alt=\"Chocolate Belga\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Chocolate Belga</a></h2>\n");
      out.write("      <strong class=\"item-price\"><del>R$46.00</del> R$30.00</strong>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Doce-de-Leite.png\" alt=\"DocedeLeite\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Doce de Leite</a></h2>\n");
      out.write("      <strong class=\"item-price\"><del>R$46.00</del> R$30.00</strong>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Nocciolina.png\" alt=\"Flocos\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Flocos</a></h2>\n");
      out.write("      <strong class=\"item-price\">R$20.00</strong>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"row\">\n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Mousse-di-Pistacchio.png\" alt=\"Mouse de Pistache\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Mouse de Pistache</a></h2>\n");
      out.write("      <strong class=\"item-price\">R$20.00</strong>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Cereja-Silvestre.png\" alt=\"Cereja\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Cereja</a></h2>\n");
      out.write("      <strong class=\"item-price\"><del>R$46.00</del> R$30.00</strong>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Maracuja.png\" alt=\"Maracuja\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Maracujá</a></h2>\n");
      out.write("      <strong class=\"item-price\"><del>R$46.00</del> R$30.00</strong>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"col-lg-3 col-md-6 col-sm-6 item-entry mb-4\">\n");
      out.write("      <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("        <img src=\"https://baciodilatte.com.br/wp-content/uploads/2021/09/Fragola.png\" alt=\"Morango\" class=\"img-fluid\">\n");
      out.write("      </a>\n");
      out.write("      <h2 class=\"item-title\"><a href=\"#\">Morango</a></h2>\n");
      out.write("      <strong class=\"item-price\">R$20.00</strong>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("           \n");
      out.write("\n");
      out.write("    <div class=\"site-blocks-cover inner-page py-5\" data-aos=\"fade\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-md-6 ml-auto order-md-2 align-self-start\">\n");
      out.write("        <div class=\"site-block-cover-content\">\n");
      out.write("     <h2 class=\"title\" style=\"color: #CF793C;\">Realize seus sonhos, torne-se um franqueado</h2>\n");
      out.write("          <h1 style=\"color: #CF793C;\">BDL</h1>\n");
      out.write("        <p class=\"text-center\"><a href=\"#\" class=\"btn btn-custom rounded-0\" style=\"background-color: #CF793C; color: #fff; font-weight: bold;\">CLIQUE AQUI</a></p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-6 order-1 align-self-center\">\n");
      out.write("        <img src=\"https://o.remove.bg/downloads/dc60dee6-478a-4da3-9d0a-76e5fadc4fb5/download-removebg-preview.png\" alt=\"Image\" class=\"img-fluid w-100 h-auto\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/components/footer.jsp", out, false);
      out.write('\n');
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
