/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-11-21 23:17:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    <!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <title>ShopMax &mdash; Colorlib e-Commerce Template</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Mukta:300,400,700\"> \n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/icomoon/style.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery-ui.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/aos.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  \n");
      out.write("  <div class=\"site-wrap\">\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <div class=\"site-navbar bg-white py-2\">\n");
      out.write("\n");
      out.write("      <div class=\"search-wrap\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <a href=\"#\" class=\"search-close js-search-close\"><span class=\"icon-close2\"></span></a>\n");
      out.write("          <form action=\"#\" method=\"post\">\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Search keyword and hit enter...\">\n");
      out.write("          </form>  \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"d-flex align-items-center justify-content-between\">\n");
      out.write("          <div class=\"logo\">\n");
      out.write("            <div class=\"site-logo\">\n");
      out.write("              <a href=\"index.html\" class=\"js-logo-clone\">ShopMax</a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"main-nav d-none d-lg-block\">\n");
      out.write("            <nav class=\"site-navigation text-right text-md-center\" role=\"navigation\">\n");
      out.write("              <ul class=\"site-menu js-clone-nav d-none d-lg-block\">\n");
      out.write("                <li class=\"has-children \">\n");
      out.write("                  <a href=\"index.html\">Home</a>\n");
      out.write("                  <ul class=\"dropdown\">\n");
      out.write("                    <li><a href=\"#\">Menu One</a></li>\n");
      out.write("                    <li><a href=\"#\">Menu Two</a></li>\n");
      out.write("                    <li><a href=\"#\">Menu Three</a></li>\n");
      out.write("                    <li class=\"has-children\">\n");
      out.write("                      <a href=\"#\">Sub Menu</a>\n");
      out.write("                      <ul class=\"dropdown\">\n");
      out.write("                        <li><a href=\"#\">Menu One</a></li>\n");
      out.write("                        <li><a href=\"#\">Menu Two</a></li>\n");
      out.write("                        <li><a href=\"#\">Menu Three</a></li>\n");
      out.write("                      </ul>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("                <li class=\"active\"><a href=\"shop.html\">Shop</a></li>\n");
      out.write("                <li><a href=\"#\">Catalogue</a></li>\n");
      out.write("                <li><a href=\"#\">New Arrivals</a></li>\n");
      out.write("                <li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </nav>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"icons\">\n");
      out.write("            <a href=\"#\" class=\"icons-btn d-inline-block js-search-open\"><span class=\"icon-search\"></span></a>\n");
      out.write("            <a href=\"#\" class=\"icons-btn d-inline-block\"><span class=\"icon-heart-o\"></span></a>\n");
      out.write("            <a href=\"cart.html\" class=\"icons-btn d-inline-block bag\">\n");
      out.write("              <span class=\"icon-shopping-bag\"></span>\n");
      out.write("              <span class=\"number\">2</span>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"#\" class=\"site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none\"><span class=\"icon-menu\"></span></a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"site-blocks-cover inner-page\" data-aos=\"fade\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-6 ml-auto order-md-2 align-self-start\">\n");
      out.write("            <div class=\"site-block-cover-content\">\n");
      out.write("            <h2 class=\"sub-title\">#New Summer Collection 2019</h2>\n");
      out.write("            <h1>Arrivals Sales</h1>\n");
      out.write("            <p><a href=\"#\" class=\"btn btn-black rounded-0\">Shop Now</a></p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-6 order-1 align-self-end\">\n");
      out.write("            <img src=\"images/model_4.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"custom-border-bottom py-3\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-12 mb-0\"><a href=\"index.html\">Home</a> <span class=\"mx-2 mb-0\">/</span> <strong class=\"text-black\">Shop</strong></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"site-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"row mb-5\">\n");
      out.write("          <div class=\"col-md-9 order-1\">\n");
      out.write("\n");
      out.write("            <div class=\"row align\">\n");
      out.write("              <div class=\"col-md-12 mb-5\">\n");
      out.write("                <div class=\"float-md-left\"><h2 class=\"text-black h5\">Shop All</h2></div>\n");
      out.write("                <div class=\"d-flex\">\n");
      out.write("                  <div class=\"dropdown mr-1 ml-md-auto\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-white btn-sm dropdown-toggle px-4\" id=\"dropdownMenuOffset\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                      Latest\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuOffset\">\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Men</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Women</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Children</a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"btn-group\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-white btn-sm dropdown-toggle px-4\" id=\"dropdownMenuReference\" data-toggle=\"dropdown\">Reference</button>\n");
      out.write("                    <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuReference\">\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Relevance</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Name, A to Z</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Name, Z to A</a>\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Price, low to high</a>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">Price, high to low</a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row mb-5\">\n");
      out.write("\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/prod_2.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Gray Shoe</a></h2>\n");
      out.write("                <strong class=\"item-price\">$20.00</strong>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/prod_3.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Blue Shoe High Heels</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/model_5.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Denim Jacket</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("\n");
      out.write("                <div class=\"star-rating\">\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/prod_1.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Leather Green Bag</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("                <div class=\"star-rating\">\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/model_1.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Smooth Cloth</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/model_7.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Yellow Jacket</a></h2>\n");
      out.write("                <strong class=\"item-price\">$58.00</strong>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/prod_2.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Gray Shoe</a></h2>\n");
      out.write("                <strong class=\"item-price\">$20.00</strong>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/prod_3.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Blue Shoe High Heels</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/model_5.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Denim Jacket</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("\n");
      out.write("                <div class=\"star-rating\">\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/prod_1.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Leather Green Bag</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("                <div class=\"star-rating\">\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                  <span class=\"icon-star2 text-warning\"></span>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/model_1.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Smooth Cloth</a></h2>\n");
      out.write("                <strong class=\"item-price\"><del>$46.00</del> $28.00</strong>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 col-md-6 item-entry mb-4\">\n");
      out.write("                <a href=\"#\" class=\"product-item md-height bg-gray d-block\">\n");
      out.write("                  <img src=\"images/model_7.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("                </a>\n");
      out.write("                <h2 class=\"item-title\"><a href=\"#\">Yellow Jacket</a></h2>\n");
      out.write("                <strong class=\"item-price\">$58.00</strong>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-12 text-center\">\n");
      out.write("                <div class=\"site-block-27\">\n");
      out.write("                  <ul>\n");
      out.write("                    <li><a href=\"#\">&lt;</a></li>\n");
      out.write("                    <li class=\"active\"><span>1</span></li>\n");
      out.write("                    <li><a href=\"#\">2</a></li>\n");
      out.write("                    <li><a href=\"#\">3</a></li>\n");
      out.write("                    <li><a href=\"#\">4</a></li>\n");
      out.write("                    <li><a href=\"#\">5</a></li>\n");
      out.write("                    <li><a href=\"#\">&gt;</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-3 order-2 mb-5 mb-md-0\">\n");
      out.write("            <div class=\"border p-4 rounded mb-4\">\n");
      out.write("              <h3 class=\"mb-3 h6 text-uppercase text-black d-block\">Categories</h3>\n");
      out.write("              <ul class=\"list-unstyled mb-0\">\n");
      out.write("                <li class=\"mb-1\"><a href=\"#\" class=\"d-flex\"><span>Men</span> <span class=\"text-black ml-auto\">(2,220)</span></a></li>\n");
      out.write("                <li class=\"mb-1\"><a href=\"#\" class=\"d-flex\"><span>Women</span> <span class=\"text-black ml-auto\">(2,550)</span></a></li>\n");
      out.write("                <li class=\"mb-1\"><a href=\"#\" class=\"d-flex\"><span>Children</span> <span class=\"text-black ml-auto\">(2,124)</span></a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"border p-4 rounded mb-4\">\n");
      out.write("              <div class=\"mb-4\">\n");
      out.write("                <h3 class=\"mb-3 h6 text-uppercase text-black d-block\">Filter by Price</h3>\n");
      out.write("                <div id=\"slider-range\" class=\"border-primary\"></div>\n");
      out.write("                <input type=\"text\" name=\"text\" id=\"amount\" class=\"form-control border-0 pl-0 bg-white\" disabled=\"\" />\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"mb-4\">\n");
      out.write("                <h3 class=\"mb-3 h6 text-uppercase text-black d-block\">Size</h3>\n");
      out.write("                <label for=\"s_sm\" class=\"d-flex\">\n");
      out.write("                  <input type=\"checkbox\" id=\"s_sm\" class=\"mr-2 mt-1\"> <span class=\"text-black\">Small (2,319)</span>\n");
      out.write("                </label>\n");
      out.write("                <label for=\"s_md\" class=\"d-flex\">\n");
      out.write("                  <input type=\"checkbox\" id=\"s_md\" class=\"mr-2 mt-1\"> <span class=\"text-black\">Medium (1,282)</span>\n");
      out.write("                </label>\n");
      out.write("                <label for=\"s_lg\" class=\"d-flex\">\n");
      out.write("                  <input type=\"checkbox\" id=\"s_lg\" class=\"mr-2 mt-1\"> <span class=\"text-black\">Large (1,392)</span>\n");
      out.write("                </label>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"mb-4\">\n");
      out.write("                <h3 class=\"mb-3 h6 text-uppercase text-black d-block\">Color</h3>\n");
      out.write("                <a href=\"#\" class=\"d-flex color-item align-items-center\" >\n");
      out.write("                  <span class=\"bg-danger color d-inline-block rounded-circle mr-2\"></span> <span class=\"text-black\">Red (2,429)</span>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#\" class=\"d-flex color-item align-items-center\" >\n");
      out.write("                  <span class=\"bg-success color d-inline-block rounded-circle mr-2\"></span> <span class=\"text-black\">Green (2,298)</span>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#\" class=\"d-flex color-item align-items-center\" >\n");
      out.write("                  <span class=\"bg-info color d-inline-block rounded-circle mr-2\"></span> <span class=\"text-black\">Blue (1,075)</span>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"#\" class=\"d-flex color-item align-items-center\" >\n");
      out.write("                  <span class=\"bg-primary color d-inline-block rounded-circle mr-2\"></span> <span class=\"text-black\">Purple (1,075)</span>\n");
      out.write("                </a>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"site-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"title-section mb-5\">\n");
      out.write("          <h2 class=\"text-uppercase\"><span class=\"d-block\">Discover</span> The Collections</h2>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row align-items-stretch\">\n");
      out.write("          <div class=\"col-lg-8\">\n");
      out.write("            <div class=\"product-item sm-height full-height bg-gray\">\n");
      out.write("              <a href=\"#\" class=\"product-category\">Women <span>25 items</span></a>\n");
      out.write("              <img src=\"images/model_4.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4\">\n");
      out.write("            <div class=\"product-item sm-height bg-gray mb-4\">\n");
      out.write("              <a href=\"#\" class=\"product-category\">Men <span>25 items</span></a>\n");
      out.write("              <img src=\"images/model_5.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"product-item sm-height bg-gray\">\n");
      out.write("              <a href=\"#\" class=\"product-category\">Shoes <span>25 items</span></a>\n");
      out.write("              <img src=\"images/model_6.png\" alt=\"Image\" class=\"img-fluid\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <footer class=\"site-footer custom-border-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-6 col-lg-3 mb-4 mb-lg-0\">\n");
      out.write("            <h3 class=\"footer-heading mb-4\">Promo</h3>\n");
      out.write("            <a href=\"#\" class=\"block-6\">\n");
      out.write("              <img src=\"images/about_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid rounded mb-4\">\n");
      out.write("              <h3 class=\"font-weight-light  mb-0\">Finding Your Perfect Shirts This Summer</h3>\n");
      out.write("              <p>Promo from  July 15 &mdash; 25, 2019</p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-5 ml-auto mb-5 mb-lg-0\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-12\">\n");
      out.write("                <h3 class=\"footer-heading mb-4\">Quick Links</h3>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6 col-lg-4\">\n");
      out.write("                <ul class=\"list-unstyled\">\n");
      out.write("                  <li><a href=\"#\">Sell online</a></li>\n");
      out.write("                  <li><a href=\"#\">Features</a></li>\n");
      out.write("                  <li><a href=\"#\">Shopping cart</a></li>\n");
      out.write("                  <li><a href=\"#\">Store builder</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6 col-lg-4\">\n");
      out.write("                <ul class=\"list-unstyled\">\n");
      out.write("                  <li><a href=\"#\">Mobile commerce</a></li>\n");
      out.write("                  <li><a href=\"#\">Dropshipping</a></li>\n");
      out.write("                  <li><a href=\"#\">Website development</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-6 col-lg-4\">\n");
      out.write("                <ul class=\"list-unstyled\">\n");
      out.write("                  <li><a href=\"#\">Point of sale</a></li>\n");
      out.write("                  <li><a href=\"#\">Hardware</a></li>\n");
      out.write("                  <li><a href=\"#\">Software</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"col-md-6 col-lg-3\">\n");
      out.write("            <div class=\"block-5 mb-5\">\n");
      out.write("              <h3 class=\"footer-heading mb-4\">Contact Info</h3>\n");
      out.write("              <ul class=\"list-unstyled\">\n");
      out.write("                <li class=\"address\">203 Fake St. Mountain View, San Francisco, California, USA</li>\n");
      out.write("                <li class=\"phone\"><a href=\"tel://23923929210\">+2 392 3929 210</a></li>\n");
      out.write("                <li class=\"email\">emailaddress@domain.com</li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"block-7\">\n");
      out.write("              <form action=\"#\" method=\"post\">\n");
      out.write("                <label for=\"email_subscribe\" class=\"footer-heading\">Subscribe</label>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control py-4\" id=\"email_subscribe\" placeholder=\"Email\">\n");
      out.write("                  <input type=\"submit\" class=\"btn btn-sm btn-primary\" value=\"Send\">\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row pt-5 mt-5 text-center\">\n");
      out.write("          <div class=\"col-md-12\">\n");
      out.write("            <p>\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\" class=\"text-primary\">Colorlib</a>\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <script src=\"js/jquery-3.3.1.min.js\"></script>\n");
      out.write("  <script src=\"js/jquery-ui.js\"></script>\n");
      out.write("  <script src=\"js/popper.min.js\"></script>\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("  <script src=\"js/aos.js\"></script>\n");
      out.write("\n");
      out.write("  <script src=\"js/main.js\"></script>\n");
      out.write("    \n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
